[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = ".next"
  functions = ".netlify/functions"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "false"
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"
  
  # Environment variables
  NEXT_PUBLIC_SUPABASE_URL = "https://xhdcccmzciblpbrcrnii.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhoZGNjY216Y2libHBicmNybmlpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkyMzg3MTAsImV4cCI6MjA1NDgxNDcxMH0.HH1tJatUQiHZC62Kl0_h7wTxrh2ZKHJAjcncKE30UYU"
  NEXT_PUBLIC_GEOAPIFY_API_KEY = "5a047258d51943729c19139c17b7ff1a"
  OPEN_ROUTER_API_KEY = "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"
  NEXT_PUBLIC_OPEN_ROUTER_API_KEY = "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"
  DISABLE_TWILIO = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  [plugins.inputs]
    external_node_modules = ["@supabase/supabase-js"]

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@supabase/supabase-js"]

[dev]
  framework = "nextjs"
  targetPort = 3000