[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_PUBLIC_SUPABASE_URL = "https://xhdcccmzciblpbrcrnii.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhoZGNjY216Y2libHBicmNybmlpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkyMzg3MTAsImV4cCI6MjA1NDgxNDcxMH0.HH1tJatUQiHZC62Kl0_h7wTxrh2ZKHJAjcncKE30UYU"
  NEXT_PUBLIC_GEOAPIFY_API_KEY = "feb86984a93a4ebeb04f26ac0d1312b9"
  OPEN_ROUTER_API_KEY = "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"
  NEXT_PUBLIC_OPEN_ROUTER_API_KEY = "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"
  DISABLE_TWILIO = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"
