[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# These redirects are unnecessary for Next.js and may conflict with its routing
# The @netlify/plugin-nextjs handles this automatically
