name: Deploy PandaTraveLog to Netlify

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Lint
        run: npm run lint || true
      
      - name: Build
        env:
          # Supabase
          SUPABASE_URL: ${{ vars.SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_URL: ${{ vars.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          
          
          # Geoapify API
          GEOAPIFY_API_KEY: ${{ secrets.GEOAPIFY_API_KEY }}
          NEXT_PUBLIC_GEOAPIFY_API_KEY: ${{ secrets.NEXT_PUBLIC_GEOAPIFY_API_KEY }}

          # Google API
          GOOGLE_OAUTH_CLIENT_ID: ${{ secrets.GOOGLE_OAUTH_CLIENT_ID }}
          
          # Gemini AI
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          NEXT_PUBLIC_GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          
          # Twilio
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          TWILIO_VERIFY_SERVICE_SECRET: ${{ secrets.TWILIO_VERIFY_SERVICE_SECRET }}
          
          # Misc
          NEXT_PUBLIC_EXCHANGE_API_KEY: ${{ secrets.NEXT_PUBLIC_EXCHANGE_API_KEY }}
          NEXT_PUBLIC_BASE_URL: ${{ vars.NEXT_PUBLIC_BASE_URL }}
          NODE_ENV: ${{ vars.NODE_ENV }}
        run: npm run build
      
      # Deploy Preview for Pull Requests
      - name: Deploy PR Preview to Netlify
        if: github.event_name == 'pull_request'
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=.next --message "Deploy PR #${{ github.event.number }} - ${{ github.event.pull_request.head.sha }}"
      
      # Deploy Production for Main Branch
      - name: Deploy Production to Netlify
        if: github.ref == 'refs/heads/main'
        uses: netlify/actions/cli@main
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=.next --prod --message "Deploy Production - ${{ github.sha }}"
